Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,6 +23,7 @@ jobs:
         run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
           cd /home/ec2-user/serengetiboard_backend # Adjust to your application path on the EC2 instance
+          npm stop || echo "Failed to stop application or no application was running."
           echo "STOPPED"
           git pull origin main  # Adjust to the branch to deploy
           echo "pulled"
