Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,10 +21,16 @@ jobs:
 
       - name: Deploy to EC2
         run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
-          cd /home/ec2-user/serengetiboard_backend # Adjust to your application path on the EC2 instance
-          git pull origin main  # Adjust to the branch to deploy
-          npm install
-          npm restart serengetiboard_backend 
-          exit
-          EOF
+        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
+        set -e  # Exit immediately if a command exits with a non-zero status
+        echo "Changing directory..."
+        cd /home/ec2-user/serengetiboard_backend || exit 1
+        echo "Pulling latest code from git..."
+        git pull origin main || exit 1
+        echo "Installing dependencies..."
+        npm install || exit 1
+        echo "Restarting application..."
+        npm restart || exit 1
+        echo "Commands executed successfully."
+        exit
+        EOF
